Fitness_All_in_One/Controllers/DietPlanController.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Fitness_All_in_One.Data;
using Fitness_All_in_One.Models;
using Fitness_All_in_One.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fitness_All_in_One.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DietPlanController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DietPlanController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dietPlans = await _context.DietPlans.ToListAsync();
            return View(dietPlans);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DietPlanModel model)
        {
            if (ModelState.IsValid)
            {
                var dietPlan = new DietPlanModel
                {
                    DietName = model.DietName,
                    Description = model.Description,
                    Gender = model.Gender,
                    StartAge = model.StartAge, 
                    EndAge = model.EndAge,
                    StartWeight = model.StartWeight,
                    EndWeight = model.EndWeight,
                    StartHeight = model.StartHeight,
                    EndHeight = model.EndHeight,
                    BMI = model.BMI,
                    Food = model.Food,
                };

                _context.Add(dietPlan);
                await _context.SaveChangesAsync();

                TempData["Message"] = $"Diet plan '{dietPlan.DietName}' has been created successfully.";
                return RedirectToAction("Index");
            }

            return View(model);
        }



        public async Task<IActionResult> Edit(int id)
        {
            var dietPlan = await _context.DietPlans.FindAsync(id);

            if (dietPlan == null)
            {
                return NotFound();
            }

            var viewModel = new DietPlanModel
            {
                Id = dietPlan.Id,
                DietName = dietPlan.DietName,
                Gender = dietPlan.Gender,
                StartAge = dietPlan.StartAge,
                EndAge = dietPlan.EndAge,
                StartWeight = dietPlan.StartWeight,
                EndWeight = dietPlan.EndWeight,
                StartHeight = dietPlan.StartHeight,
                EndHeight = dietPlan.EndHeight,
                Description = dietPlan.Description,
                BMI = dietPlan.BMI,
                Food = dietPlan.Food,

            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DietPlanModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var dietPlan = await _context.DietPlans.FindAsync(id);

                if (dietPlan == null)
                {
                    return NotFound();
                }

                dietPlan.DietName = model.DietName;
                dietPlan.Description = model.Description;
                dietPlan.Gender = model.Gender;
                dietPlan.StartAge = model.StartAge;
                dietPlan.EndAge = model.EndAge;
                dietPlan.StartWeight = model.StartWeight;
                dietPlan.EndWeight = model.EndWeight;
                dietPlan.StartHeight = model.StartHeight;
                dietPlan.EndHeight = model.EndHeight;
                dietPlan.BMI = model.BMI;
                dietPlan.Food = model.Food;

                _context.Update(dietPlan);
                await _context.SaveChangesAsync();

                TempData["Message"] = $"Diet plan '{dietPlan.DietName}' has been updated successfully.";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var dietPlan = await _context.DietPlans.FindAsync(id);
            if (dietPlan == null)
            {
                return NotFound();
            }

            return View(dietPlan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dietPlan = await _context.DietPlans.FindAsync(id);

            if (dietPlan == null)
            {
                return NotFound();
            }

            _context.DietPlans.Remove(dietPlan);
            await _context.SaveChangesAsync();

            TempData["Message"] = $"Diet plan '{dietPlan.DietName}' has been deleted successfully.";
            return RedirectToAction("Index");
        }
        public IActionResult Description(int id)
        {
            // Retrieve the diet plan with the specified ID
            var dietPlan = _context.DietPlans.FirstOrDefault(dp => dp.Id == id);

            // Pass the diet plan to the view
            return View(dietPlan);
        }

    }
}

Fitness_All_in_One/Controllers/UserDietPlanController.cs
using Fitness_All_in_One.Data;
using Fitness_All_in_One.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fitness_All_in_One.Controllers
{
    public class UserDietPlanController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        public UserDietPlanController(UserManager<ApplicationUser> userManager , ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to view the diet plans.";
                return View("Error");
            }


            double weight = double.Parse(user.Weight);
            double height = double.Parse(user.Height) / 100.0; // convert height to meters

            double bmi = weight / (height * height);

            var userDetails = new UserDetails
            {
                Name = user.Name,
                Gender = user.Gender,
                Age = user.Age,
                Weight = user.Weight,
                Height = user.Height,
                TargetWeight = user.TargetWeight,
                BMI = bmi.ToString("F") // format the BMI value as a string
            };

            return View(userDetails);
        }

        public async Task<IActionResult> GeneratePlan()
        { 

            // Get the current user's gender
            var user = await _userManager.GetUserAsync(User);
            var gender = user.Gender;

            // Retrieve all diet plans from the database that match the user's gender
            var dietPlans = await _context.DietPlans
                .Where(dp => dp.Gender == gender)
                .Select(dp => new DietPlanModel
                {
                    Description = dp.Description,
                    DietName = dp.DietName,
                    Food = dp.Food
                })
                .ToListAsync();

            if (dietPlans.Count == 0)
            {
                return NotFound();
            }

            // Pass the list of diet plans to the view
            return View(dietPlans);
        }




        [HttpGet]
        
        public IActionResult Description(int id)
        {
            // Retrieve the diet plan with the specified ID
            var dietPlan = _context.DietPlans.FirstOrDefault(dp => dp.Id == id);

            // If the diet plan is not found, return a 404 Not Found response
            if (dietPlan == null)
            {
                return NotFound();
            }

            // Pass the name of the view file to the View() method
            return View(dietPlan);

        }


    }
}

Fitness_All_in_One/Controllers/UsersController.cs
using Fitness_All_in_One.Models;
using Fitness_All_in_One.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Fitness_All_in_One.Data;

namespace Fitness_All_in_One.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        // private readonly RoleManager<IdentityRole> _roleManager;


        public UsersController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {

            _userManager = userManager;
            // _roleManager = roleManager;

        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Select(user => new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Gender = user.Gender,
                Age = user.Age,
                Weight = user.Weight,
                Height = user.Height,
                TargetWeight = user.TargetWeight,
                Email = user.Email,
                //    Roles = _userManager.GetRolesAsync(user).Result

            }).ToListAsync();

            return View(users);

        }
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var viewModel = new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Gender = user.Gender,
                Age = user.Age,
                Weight = user.Weight,
                Height = user.Height,
                TargetWeight = user.TargetWeight,
                Email = user.Email,
                /* Roles = await _userManager.GetRolesAsync(user)*/
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, UserViewModel model)
        {
            try
            {
                if (id != model.Id)
                {
                    return NotFound();
                }

                var user = await _userManager.FindByIdAsync(id);

                if (user == null)
                {
                    return NotFound();
                }

                user.Name = model.Name;
                user.Gender = model.Gender;
                user.Age = model.Age;
                user.Weight = model.Weight;
                user.Height = model.Height;
                user.TargetWeight = model.TargetWeight;
                /*user.Email = model.Email;*/

                var result = await _userManager.UpdateAsync(user);



                if (result.Succeeded)
                {
                    TempData["Message"] = $"User profile for {user.Name} has been updated successfully.";
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
            catch (Exception ex)
            {
                // log the error or handle it in some way
                return View("Error");
            }
        }
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var viewModel = new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Gender = user.Gender,
                Age = user.Age,
                Weight = user.Weight,
                Height = user.Height,
                TargetWeight = user.TargetWeight,
                Email = user.Email
            };
            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                TempData["Message"] = $"User profile of {user.Name} has been deleted successfully.";
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            var viewModel = new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Gender = user.Gender,
                Age = user.Age,
                Weight = user.Weight,
                Height = user.Height,
                TargetWeight = user.TargetWeight,
                Email = user.Email


            };
            return View("Delete", viewModel);
        }




    }


}

Fitness_All_in_One/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>All-in-one Fitness</title>
	<!-- Loading third party fonts -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|" rel="stylesheet" type="text/css">
	<link href="~/fonts/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="~/fonts/iconmoon.css" rel="stylesheet" type="text/css">
	<!-- Loading main css file -->
	<link rel="stylesheet" href="~/stylenewhome.css">

	<!--[if lt IE 9]>
	<script src="js/ie-support/html5.js"></script>
	<script src="js/ie-support/respond.js"></script>
	<![endif]-->

</head>


<body class="homepage">

	<div id="site-content">
		<header class="site-header">
			<div class="container">
				<a href="index.html" id="branding" class="pull-left">
					<i class="icon-cupcake logo"></i>
					<h1 class="site-title">All-in-one Fitness</h1>
				</a>
				<!-- Default snippet for navigation -->
				<div class="main-navigation pull-right">
					<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
					
					<ul class="menu">
						<li class="menu-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
						<li class="menu-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
							<li class="menu-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Manage User</a>
                            </li>
							<li class="menu-item">
                                <a asp-controller="DietPlan" asp-action="Index" class="nav-link text-dark">Add Diet Plan</a>
                            </li>
                        }
                        <li class="menu-item">
                            <a asp-controller="UserDietPlan" asp-action="Index" class="nav-link text-dark">Diet Plan</a>
                        </li>

					</ul> <!-- .menu -->
					<partial name="_LoginPartial" />
				</div> <!-- .main-navigation -->

				<div class="mobile-navigation"></div>
			</div>
		</header> <!-- .site-header -->
		<div class="container">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>

		<div class="hero">
			<div class="container">
				<i class="icon-cupcake logo"></i>
				<h1 class="site-title">All-in-one Fitness</h1>
				<small class="site-description">Professional Dietician</small>
			</div>
		</div>

		<main class="main-content">
			<div class="fullwidth-block cooking-section category-block">
				<div class="container">
					<figure><img src="~/dummy/cooking@2x - Copy.png" alt="cooking"></figure>
					<div class="category-content">
						<h1 class="category-title">The Importance of a Healthy Diet</h1>
						<p> A healthy diet is essential for maintaining good health and preventing chronic diseases such as obesity, diabetes, and heart disease. It is important to consume a variety of foods from all the different food groups, including fruits, vegetables, whole grains, lean proteins, and healthy fats. </p>
						<a href="#" class="button">Read more</a>
					</div> <!-- .category-content -->
				</div>
			</div> <!-- .cooking-section -->
			<div class="fullwidth-block restaurant-section category-block">
				<div class="container">
					<figure><img src="~/dummy/restaurant@2x - Copy.png" alt="restaurant"></figure>
					<div class="category-content">
						<h1 class="category-title">Importance of Portion Control and Nutrient-Dense Foods</h1>
						<p>In addition to the types of foods consumed, portion control and moderation are also important aspects of a healthy diet. It is recommended to limit the intake of processed and high-calorie foods, and to choose nutrient-dense options instead. Overall, a balanced and nutritious diet is crucial for achieving optimal health and wellness.</p>
						<a href="#" class="button">Read more</a>
					</div> <!-- .category-content -->
				</div>
			</div> <!-- .restaurant-section -->
			<div class="fullwidth-block fruits-section category-block">
				<div class="container">
					<figure><img src="~/dummy/fruits@2x - Copy.png" alt="fruits"></figure>
					<div class="category-content">
						<h1 class="category-title">The Benefits of Incorporating Fruits into a Healthy and Balanced Diet</h1>
						<p>Fruits are an important part of a healthy and balanced diet. They are loaded with essential vitamins, minerals, and fiber that are essential for maintaining good health.</p>
						<a href="#" class="button">Read more</a>
					</div> <!-- .category-content -->
				</div>
			</div> <!-- .fruits-section -->
			<div class="fullwidth-block vegetables-section category-block">
				<div class="container">
					<figure><img src="~/dummy/vegetables@2x - Copy.png" alt="vegetables"></figure>
					<div class="category-content">
						<h1 class="category-title">Understanding the Significance of Vegetables for a Healthy Lifestyle</h1>
						<p>Vegetables are an essential component of a healthy and balanced diet. They are low in calories, high in nutrients, and loaded with dietary fiber, which makes them crucial for maintaining good health.</p>
						<a href="#" class="button">Read more</a>
					</div> <!-- .category-content -->
				</div>
			</div> <!-- .vegetables-section -->

		</main> <!-- .main-content -->

		<footer class="site-footer">
			<div class="container">
				<i class="icon-cupcake logo"></i>
				<nav class="footer-navigation">
					<a href="about.html">About me</a>
					<a href="offer.html">My offer</a>
					<a href="recipe.html">Recipes</a>
					<a href="contact.html">Contact</a>
				</nav>
				<div class="subscribe">
					<form action="#">
						<input type="text" placeholder="Enter your email to join newsletter...">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="social-links">
					<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
					<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
					<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
					<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
				</div>
			</div>
		</footer>

	</div>



	<script src="~/js/jquery-1.11.1.min.js"></script>
	<script src="~/js/plugins.js"></script>
	<script src="~/js/app.js"></script>
	<script>
		$(document).ready(function () {
			$('#dynamic').DataTable();
		});
	</script>
	<script>
		$(document).ready(function () {
			$('#abc').DataTable();
		});
	</script>
	<script>
		$(document).ready(function () {
			$('#xyz').DataTable();
		});
	</script>

	<script src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)


</body>

</html>